# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Daisy Zhu 祝雨馨
tagline:          
description:      
url:              
baseurl:          /

author:
  name:           
  url:           

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/dzhuyx
